WIP: Update to support anmonteiro's httpaf
This version is supposed to work with 5.3.1 of cohttp but fails with cohttp
6.0.0~alpha with the following errors:

dune build
File "lib/paf_cohttp.ml", line 1:
Error: The implementation lib/paf_cohttp.ml
       does not match the interface lib/.paf_cohttp.objs/byte/paf_cohttp.cmi:
        The type `io' is required but not provided
       File "cohttp-lwt/src/s.ml", line 200, characters 11-32:
         Expected declaration
       The type `with_context' is required but not provided
       File "cohttp-lwt/src/s.ml", line 202, characters 11-48:
         Expected declaration
       The type `body' is required but not provided
       File "cohttp-lwt/src/s.ml", line 201, characters 11-29:
         Expected declaration
       The value `map_context' is required but not provided
       File "cohttp/src/client.ml", line 8, characters 2-68:
         Expected declaration